import type {
  CRMClient,
  CRMContact,
  CRMOpportunity,
  CRMInteraction,
  CRMTask,
  CRMCampaign,
  CRMSegment,
  CRMUser,
  CRMComment,
} from "./types"

// Usuarios del sistema
export const crmUsers: CRMUser[] = [
  {
    id: "usr-001",
    nombre: "Carlos",
    apellido: "García",
    email: "carlos.garcia@zulucrm.com",
    rol: "administrador",
    estado: "activo",
    createdAt: new Date("2024-01-01"),
    updatedAt: new Date("2024-01-01"),
  },
  {
    id: "usr-002",
    nombre: "María",
    apellido: "López",
    email: "maria.lopez@zulucrm.com",
    rol: "comercial",
    estado: "activo",
    createdAt: new Date("2024-01-15"),
    updatedAt: new Date("2024-01-15"),
  },
  {
    id: "usr-003",
    nombre: "Juan",
    apellido: "Martínez",
    email: "juan.martinez@zulucrm.com",
    rol: "comercial",
    estado: "activo",
    createdAt: new Date("2024-02-01"),
    updatedAt: new Date("2024-02-01"),
  },
  {
    id: "usr-004",
    nombre: "Ana",
    apellido: "Rodríguez",
    email: "ana.rodriguez@zulucrm.com",
    rol: "marketing",
    estado: "activo",
    createdAt: new Date("2024-02-15"),
    updatedAt: new Date("2024-02-15"),
  },
  {
    id: "usr-005",
    nombre: "Pedro",
    apellido: "Sánchez",
    email: "pedro.sanchez@zulucrm.com",
    rol: "soporte",
    estado: "activo",
    createdAt: new Date("2024-03-01"),
    updatedAt: new Date("2024-03-01"),
  },
]

// Clientes
export const crmClients: CRMClient[] = [
  {
    id: "cli-001",
    nombre: "Tecnología Avanzada S.A.",
    tipoCliente: "activo",
    segmento: "corporativo",
    industria: "Tecnología",
    cuit: "30-12345678-9",
    pais: "Argentina",
    provincia: "Buenos Aires",
    ciudad: "Buenos Aires",
    direccion: "Av. Corrientes 1234",
    telefonoPrincipal: "+54 11 4567-8900",
    emailPrincipal: "contacto@tecnoavanzada.com",
    sitioWeb: "www.tecnoavanzada.com",
    origenCliente: "web",
    estadoRelacion: "fidelizado",
    responsableId: "usr-002",
    fechaAlta: new Date("2024-01-15"),
    notasGenerales: "Cliente premium con contrato anual",
    createdAt: new Date("2024-01-15"),
    updatedAt: new Date("2024-06-01"),
  },
  {
    id: "cli-002",
    nombre: "Distribuidora del Norte",
    tipoCliente: "activo",
    segmento: "pyme",
    industria: "Distribución",
    cuit: "30-98765432-1",
    pais: "Argentina",
    provincia: "Córdoba",
    ciudad: "Córdoba",
    direccion: "Bv. San Juan 567",
    telefonoPrincipal: "+54 351 456-7890",
    emailPrincipal: "ventas@distnorte.com",
    sitioWeb: "www.distnorte.com",
    origenCliente: "referido",
    estadoRelacion: "en_negociacion",
    responsableId: "usr-003",
    fechaAlta: new Date("2024-03-20"),
    notasGenerales: "Interesado en ampliar servicios",
    createdAt: new Date("2024-03-20"),
    updatedAt: new Date("2024-05-15"),
  },
  {
    id: "cli-003",
    nombre: "Ministerio de Educación",
    tipoCliente: "prospecto",
    segmento: "gobierno",
    industria: "Gobierno",
    cuit: "30-11111111-1",
    pais: "Argentina",
    provincia: "Buenos Aires",
    ciudad: "La Plata",
    direccion: "Calle 6 entre 51 y 53",
    telefonoPrincipal: "+54 221 429-5000",
    emailPrincipal: "adquisiciones@educacion.gob.ar",
    origenCliente: "evento",
    estadoRelacion: "nuevo",
    responsableId: "usr-002",
    fechaAlta: new Date("2024-06-01"),
    notasGenerales: "Contacto en evento de tecnología educativa",
    createdAt: new Date("2024-06-01"),
    updatedAt: new Date("2024-06-01"),
  },
  {
    id: "cli-004",
    nombre: "StartupX Innovation",
    tipoCliente: "activo",
    segmento: "startup",
    industria: "Fintech",
    cuit: "30-55555555-5",
    pais: "Argentina",
    provincia: "Buenos Aires",
    ciudad: "Buenos Aires",
    direccion: "Humboldt 1550, Palermo",
    telefonoPrincipal: "+54 11 5555-1234",
    emailPrincipal: "hello@startupx.io",
    sitioWeb: "www.startupx.io",
    origenCliente: "web",
    estadoRelacion: "fidelizado",
    responsableId: "usr-003",
    fechaAlta: new Date("2024-02-10"),
    notasGenerales: "Startup en crecimiento, potencial de upselling",
    createdAt: new Date("2024-02-10"),
    updatedAt: new Date("2024-05-20"),
  },
  {
    id: "cli-005",
    nombre: "Construcciones del Sur",
    tipoCliente: "inactivo",
    segmento: "pyme",
    industria: "Construcción",
    cuit: "30-22222222-2",
    pais: "Argentina",
    provincia: "Santa Fe",
    ciudad: "Rosario",
    direccion: "Av. Pellegrini 2500",
    telefonoPrincipal: "+54 341 456-7890",
    emailPrincipal: "info@construcsur.com.ar",
    origenCliente: "llamada",
    estadoRelacion: "en_riesgo",
    responsableId: "usr-002",
    fechaAlta: new Date("2023-06-15"),
    notasGenerales: "Cliente inactivo, intentar reactivación",
    createdAt: new Date("2023-06-15"),
    updatedAt: new Date("2024-01-10"),
  },
  {
    id: "cli-006",
    nombre: "Global Services Corp",
    tipoCliente: "activo",
    segmento: "corporativo",
    industria: "Consultoría",
    cuit: "30-33333333-3",
    pais: "México",
    provincia: "CDMX",
    ciudad: "Ciudad de México",
    direccion: "Paseo de la Reforma 250",
    telefonoPrincipal: "+52 55 1234-5678",
    emailPrincipal: "contact@globalservices.mx",
    sitioWeb: "www.globalservices.mx",
    origenCliente: "campana",
    estadoRelacion: "fidelizado",
    responsableId: "usr-003",
    fechaAlta: new Date("2024-04-01"),
    notasGenerales: "Cliente internacional, facturación en USD",
    createdAt: new Date("2024-04-01"),
    updatedAt: new Date("2024-06-10"),
  },
]

// Contactos
export const crmContacts: CRMContact[] = [
  {
    id: "con-001",
    clienteId: "cli-001",
    nombre: "Roberto",
    apellido: "Fernández",
    cargo: "Director de Tecnología",
    email: "rfernandez@tecnoavanzada.com",
    telefono: "+54 11 4567-8901",
    canalPreferido: "email",
    estadoContacto: "activo",
    notas: "Tomador de decisiones principal",
    createdAt: new Date("2024-01-15"),
    updatedAt: new Date("2024-01-15"),
  },
  {
    id: "con-002",
    clienteId: "cli-001",
    nombre: "Laura",
    apellido: "Gómez",
    cargo: "Gerente de Compras",
    email: "lgomez@tecnoavanzada.com",
    telefono: "+54 11 4567-8902",
    canalPreferido: "telefono",
    estadoContacto: "activo",
    notas: "Maneja presupuestos y aprobaciones",
    createdAt: new Date("2024-01-20"),
    updatedAt: new Date("2024-01-20"),
  },
  {
    id: "con-003",
    clienteId: "cli-002",
    nombre: "Miguel",
    apellido: "Torres",
    cargo: "Gerente General",
    email: "mtorres@distnorte.com",
    telefono: "+54 351 456-7891",
    canalPreferido: "whatsapp",
    estadoContacto: "activo",
    notas: "Prefiere comunicación por WhatsApp",
    createdAt: new Date("2024-03-20"),
    updatedAt: new Date("2024-03-20"),
  },
  {
    id: "con-004",
    clienteId: "cli-003",
    nombre: "Claudia",
    apellido: "Méndez",
    cargo: "Directora de Adquisiciones",
    email: "cmendez@educacion.gob.ar",
    telefono: "+54 221 429-5001",
    canalPreferido: "email",
    estadoContacto: "activo",
    notas: "Contacto principal para licitaciones",
    createdAt: new Date("2024-06-01"),
    updatedAt: new Date("2024-06-01"),
  },
  {
    id: "con-005",
    clienteId: "cli-004",
    nombre: "Martín",
    apellido: "Acosta",
    cargo: "CEO",
    email: "martin@startupx.io",
    telefono: "+54 11 5555-1235",
    canalPreferido: "email",
    estadoContacto: "activo",
    notas: "Fundador y CEO, muy accesible",
    createdAt: new Date("2024-02-10"),
    updatedAt: new Date("2024-02-10"),
  },
  {
    id: "con-006",
    clienteId: "cli-006",
    nombre: "Patricia",
    apellido: "Vega",
    cargo: "VP Operations",
    email: "pvega@globalservices.mx",
    telefono: "+52 55 1234-5679",
    canalPreferido: "videollamada",
    estadoContacto: "activo",
    notas: "Prefiere videollamadas por zona horaria",
    createdAt: new Date("2024-04-01"),
    updatedAt: new Date("2024-04-01"),
  },
]

// Oportunidades
export const crmOpportunities: CRMOpportunity[] = [
  {
    id: "opp-001",
    clienteId: "cli-001",
    contactoPrincipalId: "con-001",
    titulo: "Implementación ERP Completo",
    etapa: "negociacion",
    probabilidad: 75,
    montoEstimado: 150000,
    moneda: "USD",
    fechaApertura: new Date("2024-03-01"),
    fechaEstimadaCierre: new Date("2024-07-15"),
    responsableId: "usr-002",
    origen: "web",
    notas: "Cliente interesado en suite completa",
    createdAt: new Date("2024-03-01"),
    updatedAt: new Date("2024-06-15"),
  },
  {
    id: "opp-002",
    clienteId: "cli-002",
    contactoPrincipalId: "con-003",
    titulo: "Módulo de Inventario",
    etapa: "propuesta",
    probabilidad: 60,
    montoEstimado: 35000,
    moneda: "USD",
    fechaApertura: new Date("2024-04-15"),
    fechaEstimadaCierre: new Date("2024-08-01"),
    responsableId: "usr-003",
    origen: "referido",
    notas: "Necesitan urgente control de stock",
    createdAt: new Date("2024-04-15"),
    updatedAt: new Date("2024-06-01"),
  },
  {
    id: "opp-003",
    clienteId: "cli-003",
    contactoPrincipalId: "con-004",
    titulo: "Sistema de Gestión Educativa",
    etapa: "calificado",
    probabilidad: 40,
    montoEstimado: 500000,
    moneda: "ARS",
    fechaApertura: new Date("2024-06-05"),
    fechaEstimadaCierre: new Date("2024-12-01"),
    responsableId: "usr-002",
    origen: "evento",
    notas: "Proceso de licitación pública",
    createdAt: new Date("2024-06-05"),
    updatedAt: new Date("2024-06-10"),
  },
  {
    id: "opp-004",
    clienteId: "cli-004",
    contactoPrincipalId: "con-005",
    titulo: "Upgrade a Plan Enterprise",
    etapa: "cerrado_ganado",
    probabilidad: 100,
    montoEstimado: 24000,
    moneda: "USD",
    fechaApertura: new Date("2024-05-01"),
    fechaEstimadaCierre: new Date("2024-05-30"),
    responsableId: "usr-003",
    origen: "web",
    notas: "Upselling exitoso",
    createdAt: new Date("2024-05-01"),
    updatedAt: new Date("2024-05-30"),
  },
  {
    id: "opp-005",
    clienteId: "cli-005",
    contactoPrincipalId: undefined,
    titulo: "Renovación de Contrato",
    etapa: "cerrado_perdido",
    probabilidad: 0,
    montoEstimado: 15000,
    moneda: "USD",
    fechaApertura: new Date("2024-01-15"),
    fechaEstimadaCierre: new Date("2024-03-01"),
    responsableId: "usr-002",
    origen: "llamada",
    motivoPerdida: "Problemas presupuestarios del cliente",
    notas: "Cliente decidió pausar inversiones",
    createdAt: new Date("2024-01-15"),
    updatedAt: new Date("2024-03-01"),
  },
  {
    id: "opp-006",
    clienteId: "cli-006",
    contactoPrincipalId: "con-006",
    titulo: "Expansión Regional LATAM",
    etapa: "lead",
    probabilidad: 25,
    montoEstimado: 200000,
    moneda: "USD",
    fechaApertura: new Date("2024-06-15"),
    fechaEstimadaCierre: new Date("2025-01-15"),
    responsableId: "usr-003",
    origen: "campana",
    notas: "Interés inicial en expandir a toda LATAM",
    createdAt: new Date("2024-06-15"),
    updatedAt: new Date("2024-06-15"),
  },
]

// Interacciones
export const crmInteractions: CRMInteraction[] = [
  {
    id: "int-001",
    clienteId: "cli-001",
    contactoId: "con-001",
    oportunidadId: "opp-001",
    tipoInteraccion: "reunion",
    canal: "videollamada",
    fechaHora: new Date("2024-06-10T10:00:00"),
    usuarioResponsableId: "usr-002",
    resultado: "exitosa",
    descripcion: "Presentación de propuesta técnica. Cliente muy interesado, solicita demo personalizada.",
    createdAt: new Date("2024-06-10"),
    updatedAt: new Date("2024-06-10"),
  },
  {
    id: "int-002",
    clienteId: "cli-001",
    contactoId: "con-002",
    oportunidadId: "opp-001",
    tipoInteraccion: "email",
    canal: "email",
    fechaHora: new Date("2024-06-12T14:30:00"),
    usuarioResponsableId: "usr-002",
    resultado: "exitosa",
    descripcion: "Envío de cotización formal con detalle de módulos y precios.",
    createdAt: new Date("2024-06-12"),
    updatedAt: new Date("2024-06-12"),
  },
  {
    id: "int-003",
    clienteId: "cli-002",
    contactoId: "con-003",
    oportunidadId: "opp-002",
    tipoInteraccion: "llamada",
    canal: "telefono",
    fechaHora: new Date("2024-06-08T11:00:00"),
    usuarioResponsableId: "usr-003",
    resultado: "exitosa",
    descripcion: "Llamada de seguimiento. Confirmó recepción de propuesta, está en evaluación.",
    createdAt: new Date("2024-06-08"),
    updatedAt: new Date("2024-06-08"),
  },
  {
    id: "int-004",
    clienteId: "cli-003",
    contactoId: "con-004",
    oportunidadId: "opp-003",
    tipoInteraccion: "visita",
    canal: "presencial",
    fechaHora: new Date("2024-06-05T09:00:00"),
    usuarioResponsableId: "usr-002",
    resultado: "exitosa",
    descripcion: "Visita a oficinas del ministerio. Presentación institucional y relevamiento de necesidades.",
    createdAt: new Date("2024-06-05"),
    updatedAt: new Date("2024-06-05"),
  },
  {
    id: "int-005",
    clienteId: "cli-004",
    contactoId: "con-005",
    oportunidadId: "opp-004",
    tipoInteraccion: "llamada",
    canal: "telefono",
    fechaHora: new Date("2024-05-28T16:00:00"),
    usuarioResponsableId: "usr-003",
    resultado: "exitosa",
    descripcion: "Llamada de cierre. Cliente confirmó upgrade a plan Enterprise.",
    createdAt: new Date("2024-05-28"),
    updatedAt: new Date("2024-05-28"),
  },
  {
    id: "int-006",
    clienteId: "cli-005",
    contactoId: undefined,
    oportunidadId: "opp-005",
    tipoInteraccion: "email",
    canal: "email",
    fechaHora: new Date("2024-02-25T10:00:00"),
    usuarioResponsableId: "usr-002",
    resultado: "sin_respuesta",
    descripcion: "Intento de contacto para renovación. Sin respuesta.",
    createdAt: new Date("2024-02-25"),
    updatedAt: new Date("2024-02-25"),
  },
]

// Tareas
export const crmTasks: CRMTask[] = [
  {
    id: "tsk-001",
    clienteId: "cli-001",
    oportunidadId: "opp-001",
    asignadoAId: "usr-002",
    titulo: "Preparar demo personalizada",
    descripcion: "Configurar ambiente de demo con datos relevantes para el cliente",
    tipoTarea: "preparar_propuesta",
    fechaVencimiento: new Date("2024-06-20"),
    prioridad: "alta",
    estado: "en_curso",
    createdAt: new Date("2024-06-10"),
    updatedAt: new Date("2024-06-15"),
  },
  {
    id: "tsk-002",
    clienteId: "cli-002",
    oportunidadId: "opp-002",
    asignadoAId: "usr-003",
    titulo: "Llamar para seguimiento de propuesta",
    descripcion: "Consultar estado de evaluación de la propuesta enviada",
    tipoTarea: "llamar",
    fechaVencimiento: new Date("2024-06-18"),
    prioridad: "media",
    estado: "pendiente",
    createdAt: new Date("2024-06-08"),
    updatedAt: new Date("2024-06-08"),
  },
  {
    id: "tsk-003",
    clienteId: "cli-003",
    oportunidadId: "opp-003",
    asignadoAId: "usr-002",
    titulo: "Enviar documentación técnica",
    descripcion: "Preparar y enviar especificaciones técnicas para licitación",
    tipoTarea: "enviar_email",
    fechaVencimiento: new Date("2024-06-25"),
    prioridad: "alta",
    estado: "pendiente",
    createdAt: new Date("2024-06-05"),
    updatedAt: new Date("2024-06-05"),
  },
  {
    id: "tsk-004",
    clienteId: "cli-004",
    oportunidadId: undefined,
    asignadoAId: "usr-003",
    titulo: "Onboarding plan Enterprise",
    descripcion: "Coordinar capacitación y migración a nuevo plan",
    tipoTarea: "seguimiento",
    fechaVencimiento: new Date("2024-06-15"),
    prioridad: "alta",
    estado: "completada",
    fechaCompletado: new Date("2024-06-14"),
    createdAt: new Date("2024-05-30"),
    updatedAt: new Date("2024-06-14"),
  },
  {
    id: "tsk-005",
    clienteId: "cli-005",
    oportunidadId: undefined,
    asignadoAId: "usr-002",
    titulo: "Campaña de reactivación",
    descripcion: "Contactar para ofrecer promoción de reactivación",
    tipoTarea: "llamar",
    fechaVencimiento: new Date("2024-06-10"),
    prioridad: "baja",
    estado: "vencida",
    createdAt: new Date("2024-06-01"),
    updatedAt: new Date("2024-06-11"),
  },
  {
    id: "tsk-006",
    clienteId: "cli-006",
    oportunidadId: "opp-006",
    asignadoAId: "usr-003",
    titulo: "Agendar videollamada inicial",
    descripcion: "Coordinar primera reunión de discovery con VP Operations",
    tipoTarea: "llamar",
    fechaVencimiento: new Date("2024-06-22"),
    prioridad: "media",
    estado: "pendiente",
    createdAt: new Date("2024-06-15"),
    updatedAt: new Date("2024-06-15"),
  },
]

// Campañas
export const crmCampaigns: CRMCampaign[] = [
  {
    id: "cmp-001",
    nombre: "Lanzamiento Q2 2024",
    tipoCampana: "email",
    objetivo: "generacion_leads",
    fechaInicio: new Date("2024-04-01"),
    fechaFin: new Date("2024-04-30"),
    presupuestoEstimado: 5000,
    presupuestoGastado: 4500,
    responsableId: "usr-004",
    notas: "Campaña de email marketing para nuevos productos Q2",
    leadsGenerados: 45,
    oportunidadesGeneradas: 12,
    negociosGanados: 3,
    createdAt: new Date("2024-03-15"),
    updatedAt: new Date("2024-05-01"),
  },
  {
    id: "cmp-002",
    nombre: "Evento Tech Summit 2024",
    tipoCampana: "evento",
    objetivo: "generacion_leads",
    fechaInicio: new Date("2024-06-01"),
    fechaFin: new Date("2024-06-02"),
    presupuestoEstimado: 15000,
    presupuestoGastado: 14200,
    responsableId: "usr-004",
    notas: "Participación como sponsor en evento de tecnología",
    leadsGenerados: 78,
    oportunidadesGeneradas: 8,
    negociosGanados: 0,
    createdAt: new Date("2024-04-01"),
    updatedAt: new Date("2024-06-10"),
  },
  {
    id: "cmp-003",
    nombre: "Redes Sociales Junio",
    tipoCampana: "redes_sociales",
    objetivo: "branding",
    fechaInicio: new Date("2024-06-01"),
    fechaFin: new Date("2024-06-30"),
    presupuestoEstimado: 3000,
    presupuestoGastado: 1800,
    responsableId: "usr-004",
    notas: "Campaña de awareness en LinkedIn y Twitter",
    leadsGenerados: 22,
    oportunidadesGeneradas: 4,
    negociosGanados: 0,
    createdAt: new Date("2024-05-25"),
    updatedAt: new Date("2024-06-15"),
  },
  {
    id: "cmp-004",
    nombre: "Recuperación Clientes Inactivos",
    tipoCampana: "email",
    objetivo: "recuperacion",
    fechaInicio: new Date("2024-05-15"),
    fechaFin: new Date("2024-06-15"),
    presupuestoEstimado: 2000,
    presupuestoGastado: 1500,
    responsableId: "usr-004",
    segmentoObjetivoId: "seg-002",
    notas: "Campaña de reactivación con oferta especial",
    leadsGenerados: 8,
    oportunidadesGeneradas: 3,
    negociosGanados: 1,
    createdAt: new Date("2024-05-10"),
    updatedAt: new Date("2024-06-15"),
  },
]

// Segmentos
export const crmSegments: CRMSegment[] = [
  {
    id: "seg-001",
    nombre: "Clientes Premium",
    descripcion: "Clientes corporativos con facturación anual mayor a USD 50,000",
    criterios: [
      { campo: "segmento", operador: "igual", valor: "corporativo" },
      { campo: "tipoCliente", operador: "igual", valor: "activo" },
    ],
    tipoSegmento: "dinamico",
    cantidadClientes: 2,
    createdAt: new Date("2024-01-01"),
    updatedAt: new Date("2024-06-01"),
  },
  {
    id: "seg-002",
    nombre: "Clientes Inactivos",
    descripcion: "Clientes sin actividad en los últimos 6 meses",
    criterios: [
      { campo: "tipoCliente", operador: "igual", valor: "inactivo" },
    ],
    tipoSegmento: "dinamico",
    cantidadClientes: 1,
    createdAt: new Date("2024-02-01"),
    updatedAt: new Date("2024-06-01"),
  },
  {
    id: "seg-003",
    nombre: "Prospectos Gobierno",
    descripcion: "Prospectos del sector gobierno",
    criterios: [
      { campo: "segmento", operador: "igual", valor: "gobierno" },
      { campo: "tipoCliente", operador: "igual", valor: "prospecto" },
    ],
    tipoSegmento: "dinamico",
    cantidadClientes: 1,
    createdAt: new Date("2024-03-01"),
    updatedAt: new Date("2024-06-01"),
  },
  {
    id: "seg-004",
    nombre: "Startups Tech",
    descripcion: "Startups del sector tecnología y fintech",
    criterios: [
      { campo: "segmento", operador: "igual", valor: "startup" },
      { campo: "industria", operador: "contiene", valor: "tech" },
    ],
    tipoSegmento: "estatico",
    cantidadClientes: 1,
    createdAt: new Date("2024-04-01"),
    updatedAt: new Date("2024-06-01"),
  },
]

// Comentarios
export const crmComments: CRMComment[] = [
  {
    id: "com-001",
    usuarioId: "usr-002",
    referenciaId: "cli-001",
    referenciaTipo: "cliente",
    texto: "Excelente relación con el cliente. Muy receptivo a nuevas propuestas.",
    fechaHora: new Date("2024-06-10T11:30:00"),
    createdAt: new Date("2024-06-10"),
    updatedAt: new Date("2024-06-10"),
  },
  {
    id: "com-002",
    usuarioId: "usr-003",
    referenciaId: "opp-002",
    referenciaTipo: "oportunidad",
    texto: "El cliente mencionó que también están evaluando competidores. Priorizar seguimiento.",
    fechaHora: new Date("2024-06-08T11:30:00"),
    createdAt: new Date("2024-06-08"),
    updatedAt: new Date("2024-06-08"),
  },
  {
    id: "com-003",
    usuarioId: "usr-002",
    referenciaId: "tsk-003",
    referenciaTipo: "tarea",
    texto: "Solicitar apoyo de equipo técnico para la documentación.",
    fechaHora: new Date("2024-06-06T09:00:00"),
    createdAt: new Date("2024-06-06"),
    updatedAt: new Date("2024-06-06"),
  },
]

// Helper functions
export function getClientById(id: string): CRMClient | undefined {
  return crmClients.find(c => c.id === id)
}

export function getContactById(id: string): CRMContact | undefined {
  return crmContacts.find(c => c.id === id)
}

export function getContactsByClientId(clientId: string): CRMContact[] {
  return crmContacts.filter(c => c.clienteId === clientId)
}

export function getOpportunitiesByClientId(clientId: string): CRMOpportunity[] {
  return crmOpportunities.filter(o => o.clienteId === clientId)
}

export function getInteractionsByClientId(clientId: string): CRMInteraction[] {
  return crmInteractions.filter(i => i.clienteId === clientId)
}

export function getTasksByClientId(clientId: string): CRMTask[] {
  return crmTasks.filter(t => t.clienteId === clientId)
}

export function getUserById(id: string): CRMUser | undefined {
  return crmUsers.find(u => u.id === id)
}

export function getCommentsByReference(referenciaId: string, referenciaTipo: string): CRMComment[] {
  return crmComments.filter(c => c.referenciaId === referenciaId && c.referenciaTipo === referenciaTipo)
}

// Dashboard stats
export function getDashboardStats() {
  const clientesPorEstado = {
    prospecto: crmClients.filter(c => c.tipoCliente === 'prospecto').length,
    activo: crmClients.filter(c => c.tipoCliente === 'activo').length,
    inactivo: crmClients.filter(c => c.tipoCliente === 'inactivo').length,
    perdido: crmClients.filter(c => c.tipoCliente === 'perdido').length,
  }

  const oportunidadesPorEtapa = {
    lead: crmOpportunities.filter(o => o.etapa === 'lead').length,
    calificado: crmOpportunities.filter(o => o.etapa === 'calificado').length,
    propuesta: crmOpportunities.filter(o => o.etapa === 'propuesta').length,
    negociacion: crmOpportunities.filter(o => o.etapa === 'negociacion').length,
    cerrado_ganado: crmOpportunities.filter(o => o.etapa === 'cerrado_ganado').length,
    cerrado_perdido: crmOpportunities.filter(o => o.etapa === 'cerrado_perdido').length,
  }

  const montoTotalPipeline = crmOpportunities
    .filter(o => !['cerrado_ganado', 'cerrado_perdido'].includes(o.etapa))
    .reduce((sum, o) => sum + o.montoEstimado, 0)

  const montoGanado = crmOpportunities
    .filter(o => o.etapa === 'cerrado_ganado')
    .reduce((sum, o) => sum + o.montoEstimado, 0)

  const tareasPendientes = crmTasks.filter(t => t.estado === 'pendiente').length
  const tareasCompletadas = crmTasks.filter(t => t.estado === 'completada').length
  const tareasVencidas = crmTasks.filter(t => t.estado === 'vencida').length

  const tareasProximasAVencer = crmTasks.filter(t => {
    if (t.estado !== 'pendiente') return false
    const diasRestantes = Math.ceil((t.fechaVencimiento.getTime() - new Date().getTime()) / (1000 * 60 * 60 * 24))
    return diasRestantes <= 7 && diasRestantes >= 0
  })

  return {
    totalClientes: crmClients.length,
    clientesPorEstado,
    totalOportunidades: crmOpportunities.length,
    oportunidadesPorEtapa,
    montoTotalPipeline,
    montoGanado,
    tareasPendientes,
    tareasCompletadas,
    tareasVencidas,
    tareasProximasAVencer,
    totalInteracciones: crmInteractions.length,
    totalCampanas: crmCampaigns.length,
  }
}
