import {
  Package,
  ShoppingCart,
  Truck,
  Calculator,
  LayoutDashboard,
  Boxes,
  Warehouse,
  Tags,
  ArrowLeftRight,
  Users,
  FileText,
  Receipt,
  BarChart3,
  Building2,
  BookOpen,
  Wallet,
  PiggyBank,
  HeartHandshake,
  Contact,
  Target,
  Megaphone,
  CalendarCheck,
  FolderKanban,
  UserCircle,
  MessageSquare,
  Filter,
  Phone,
  Headset,
  LifeBuoy,
  Ticket,
  Wrench,
  Clock,
  BookOpenCheck,
  FileCheck,
  Shield,
  Zap,
  Briefcase,
  GitBranch,
  FileStack,
  CreditCard,
  DollarSign,
  CalendarDays,
  Percent,
  UserCog,
} from "lucide-react"

export const navigation = [
  {
    title: "Dashboard",
    url: "/",
    icon: LayoutDashboard,
  },
  {
    title: "ZULU - Proyectos",
    url: "/proyectos",
    icon: Briefcase,
    items: [
      { title: "Dashboard", url: "/proyectos" },
      { title: "Proyectos", url: "/proyectos/lista" },
      { title: "Obras", url: "/proyectos/obras" },
      { title: "Tareas", url: "/proyectos/tareas" },
      { title: "Equipo", url: "/proyectos/equipo" },
      { title: "Presupuestos", url: "/proyectos/presupuestos" },
      { title: "Tiempo", url: "/proyectos/tiempo" },
      { title: "Analíticas", url: "/proyectos/analiticas" },
    ],
  },
  {
    title: "THOR - BI + IA",
    url: "/thor",
    icon: Zap,
    items: [
      { title: "Dashboard", url: "/thor" },
      { title: "Sugerencias IA", url: "/thor/sugerencias" },
      { title: "Mejores Márgenes", url: "/thor/margenes" },
      { title: "KPIs y Predicciones", url: "/thor/kpis" },
      { title: "Ranking Vendedores", url: "/thor/vendedores" },
      { title: "Ranking Cajeros", url: "/thor/cajeros" },
      { title: "Análisis Competencia", url: "/thor/competencia" },
    ],
  },
  {
    title: "Compras",
    url: "/compras",
    icon: Truck,
    items: [
      { title: "Dashboard", url: "/compras" },
      { title: "Proveedores", url: "/compras/proveedores" },
      { title: "Cotizaciones", url: "/compras/cotizaciones" },
      { title: "Requisiciones", url: "/compras/requisiciones" },
      { title: "Órdenes de Compra", url: "/compras/ordenes" },
      { title: "Recepciones", url: "/compras/recepciones" },
      { title: "Solicitudes", url: "/compras/solicitudes" },
      { title: "Facturas", url: "/compras/facturas" },
      { title: "Notas de Crédito", url: "/compras/notas-credito" },
      { title: "Devoluciones", url: "/compras/devoluciones" },
      { title: "Remitos", url: "/compras/remitos" },
      { title: "Ajustes", url: "/compras/ajustes" },
      { title: "Imputaciones", url: "/compras/imputaciones" },
      { title: "Cedulones", url: "/compras/cedulones" },
      { title: "Reportes", url: "/compras/reportes" },
    ],
  },
  {
    title: "Almacenes WMS",
    url: "/almacenes",
    icon: Warehouse,
    items: [
      { title: "Dashboard", url: "/almacenes" },
      { title: "Almacenes", url: "/almacenes/plantas" },
      { title: "Regiones", url: "/almacenes/regiones" },
      { title: "Zonas", url: "/almacenes/zonas" },
      { title: "Inventario WMS", url: "/almacenes/inventario" },
      { title: "Recepciones", url: "/almacenes/recepciones" },
      { title: "Picking", url: "/almacenes/picking" },
      { title: "Conteos", url: "/almacenes/conteos" },
      { title: "Reportes", url: "/almacenes/reportes" },
      { title: "Carta de Porte", url: "/almacenes/carta-porte" },
      { title: "Órdenes de Trabajo", url: "/almacenes/ordenes-trabajo" },
      { title: "Producción", url: "/almacenes/produccion" },
      { title: "Fórmulas de Producción", url: "/almacenes/formulas-produccion" },
      { title: "Transportistas", url: "/almacenes/transportistas" },
    ],
  },
  {
    title: "Inventario Comercial",
    url: "/inventario",
    icon: Package,
    items: [
      { title: "Dashboard", url: "/inventario" },
      { title: "Productos", url: "/inventario/productos" },
      { title: "Marcas", url: "/inventario/marcas" },
      { title: "Unidades", url: "/inventario/unidades" },
      { title: "Atributos", url: "/inventario/atributos" },
      { title: "Almacenes", url: "/inventario/almacenes" },
      { title: "Categorías", url: "/inventario/categorias" },
      { title: "Movimientos", url: "/inventario/movimientos" },
    ],
  },
  {
    title: "Ventas",
    url: "/ventas",
    icon: ShoppingCart,
    items: [
      { title: "Dashboard", url: "/ventas" },
      { title: "Clientes", url: "/ventas/clientes" },
      { title: "Productos", url: "/ventas/productos" },
      { title: "Listas de Precios", url: "/ventas/listas-precios" },
      { title: "Pedidos", url: "/ventas/pedidos" },
      { title: "Remitos", url: "/ventas/remitos" },
      { title: "Facturas", url: "/ventas/facturas" },
      { title: "Notas de Crédito", url: "/ventas/notas-credito" },
      { title: "Notas de Débito", url: "/ventas/notas-debito" },
      { title: "Devoluciones", url: "/ventas/devoluciones" },
      { title: "Ajustes", url: "/ventas/ajustes" },
      { title: "Cobros", url: "/ventas/cobros" },
      { title: "Operaciones", url: "/ventas/operaciones" },
      { title: "Cheques", url: "/ventas/cheques" },
      { title: "Imputaciones", url: "/ventas/imputaciones" },
      { title: "Cuenta Corriente", url: "/ventas/cuenta-corriente" },
      { title: "Descuentos Comerciales", url: "/ventas/descuentos" },
      { title: "Puntos de Facturación", url: "/ventas/puntos-facturacion" },
      { title: "Reportes", url: "/ventas/reportes" },
    ],
  },
  {
    title: "Contabilidad",
    url: "/contabilidad",
    icon: Calculator,
    items: [
      { title: "Plan de Cuentas", url: "/contabilidad/cuentas" },
      { title: "Asientos", url: "/contabilidad/asientos" },
      { title: "Pagos y Cobros", url: "/contabilidad/pagos" },
      { title: "Ingresos", url: "/contabilidad/ingresos" },
      { title: "Egresos", url: "/contabilidad/egresos" },
      { title: "Vales", url: "/contabilidad/vales" },
      { title: "Reintegros", url: "/contabilidad/reintegros" },
      { title: "Transferencias", url: "/contabilidad/transferencias" },
      { title: "Cajas", url: "/contabilidad/cajas" },
      { title: "Cheques", url: "/contabilidad/cheques" },
      { title: "Cotizaciones", url: "/contabilidad/cotizaciones" },
      { title: "Centros de Costo", url: "/contabilidad/centros-costo" },
      { title: "Períodos IVA", url: "/contabilidad/periodos-iva" },
      { title: "Retenciones", url: "/contabilidad/retenciones" },
      { title: "CAE y Timbrado", url: "/contabilidad/cae-timbrado" },
      { title: "Anulaciones", url: "/contabilidad/anulaciones" },
      { title: "Desimputaciones", url: "/contabilidad/desimputaciones" },
      { title: "Reportes", url: "/contabilidad/reportes" },
    ],
  },
  {
    title: "Maestros",
    url: "/maestros",
    icon: Building2,
    items: [
      { title: "Dashboard", url: "/maestros" },
      { title: "Jurisdicciones", url: "/maestros/jurisdicciones" },
      { title: "Sucursales", url: "/maestros/sucursales" },
    ],
  },
  {
    title: "Colegio",
    url: "/colegio",
    icon: BookOpenCheck,
    items: [
      { title: "Dashboard", url: "/colegio" },
      { title: "Cartera", url: "/colegio/cartera" },
      { title: "Planes y Lotes", url: "/colegio/planes" },
    ],
  },
  {
    title: "Empleados / RRHH",
    url: "/empleados",
    icon: UserCog,
    items: [
      { title: "Dashboard", url: "/empleados" },
      { title: "Legajos", url: "/empleados/legajos" },
      { title: "Nómina y Liquidaciones", url: "/empleados/liquidaciones" },
    ],
  },
  {
    title: "CRM",
    url: "/crm",
    icon: HeartHandshake,
    items: [
      { title: "Dashboard", url: "/crm" },
      { title: "Clientes", url: "/crm/clientes" },
      { title: "Contactos", url: "/crm/contactos" },
      { title: "Oportunidades", url: "/crm/oportunidades" },
      { title: "Interacciones", url: "/crm/interacciones" },
      { title: "Tareas", url: "/crm/tareas" },
      { title: "Campañas", url: "/crm/campanas" },
      { title: "Segmentos", url: "/crm/segmentos" },
      { title: "Usuarios", url: "/crm/usuarios" },
      { title: "Reportes", url: "/crm/reportes" },
    ],
  },
  {
    title: "Help Desk",
    url: "/helpdesk",
    icon: LifeBuoy,
    items: [
      { title: "Dashboard", url: "/helpdesk" },
      { title: "Tickets", url: "/helpdesk/tickets" },
      { title: "Ordenes de Servicio", url: "/helpdesk/ordenes" },
      { title: "Servicios", url: "/helpdesk/servicios" },
      { title: "Clientes", url: "/helpdesk/clientes" },
      { title: "Contratos", url: "/helpdesk/contratos" },
      { title: "SLAs", url: "/helpdesk/slas" },
      { title: "Facturacion", url: "/helpdesk/facturacion" },
      { title: "Agentes", url: "/helpdesk/agentes" },
      { title: "Reportes", url: "/helpdesk/reportes" },
    ],
  },
]

export const moduleIcons = {
  productos: Boxes,
  almacenes: Warehouse,
  categorias: Tags,
  movimientos: ArrowLeftRight,
  clientes: Users,
  pedidos: FileText,
  facturas: Receipt,
  reportes: BarChart3,

  cuentas: BookOpen,
  asientos: Wallet,
  pagos: PiggyBank,
  ingresos: CreditCard,
  egresos: DollarSign,
  vales: Ticket,
  reintegros: ArrowLeftRight,
  transferencias: GitBranch,
  retenciones: Percent,
  cheques: CreditCard,
  periodos: CalendarDays,
  anulaciones: Shield,
  desimputaciones: FileStack,
  contactos: Contact,
  oportunidades: Target,
  campanas: Megaphone,
  actividades: CalendarCheck,
  pipeline: FolderKanban,
  interacciones: Phone,
  tareas: CalendarCheck,
  segmentos: Filter,
  usuarios: UserCircle,
  comentarios: MessageSquare,
  // Help Desk
  tickets: Ticket,
  servicios: Wrench,
  contratos: FileCheck,
  slas: Clock,
  facturacion: Receipt,
  agentes: Headset,
  departamentos: Building2,
}
