import type {
  ThorProduct,
  AIRecommendation,
  Vendedor,
  VendedorMetrica,
  Cajero,
  CajeroMetrica,
  Competidor,
  PrecioCompetidor,
  HistoricoVenta,
} from "./thor-types"

export const thorProducts: ThorProduct[] = [
  {
    id: "prod-001",
    sku: "LACT-001",
    nombre: "Leche Descremada 1L",
    categoria: "Lácteos",
    marca: "Marca Premium",
    costoProm: 45,
    precioVenta: 89,
    stock: 450,
    unidadMedida: "unid",
    proveedor: "Lácteos del Sur",
    margenPorcentaje: 49.4,
    margenDolar: 44,
    rotacionDias: 3,
    ventasUltimos3Meses: 12000,
    ventasUltimos6Meses: 24000,
    ventasUltimos12Meses: 48000,
    createdAt: new Date("2024-01-15"),
    updatedAt: new Date("2024-02-06"),
  },
  {
    id: "prod-002",
    sku: "BEBI-001",
    nombre: "Gaseosa 2L",
    categoria: "Bebidas",
    marca: "Bebida Popular",
    costoProm: 80,
    precioVenta: 159,
    stock: 320,
    unidadMedida: "unid",
    proveedor: "Bebidas Nacionales",
    margenPorcentaje: 49.7,
    margenDolar: 79,
    rotacionDias: 5,
    ventasUltimos3Meses: 8500,
    ventasUltimos6Meses: 17000,
    ventasUltimos12Meses: 34000,
    createdAt: new Date("2024-01-15"),
    updatedAt: new Date("2024-02-06"),
  },
  {
    id: "prod-003",
    sku: "PAN-001",
    nombre: "Pan de Molde Integral",
    categoria: "Panadería",
    marca: "Panadería Artesanal",
    costoProm: 35,
    precioVenta: 89,
    stock: 280,
    unidadMedida: "unid",
    proveedor: "Molinos Unidos",
    margenPorcentaje: 60.7,
    margenDolar: 54,
    rotacionDias: 2,
    ventasUltimos3Meses: 14200,
    ventasUltimos6Meses: 28500,
    ventasUltimos12Meses: 57000,
    createdAt: new Date("2024-01-15"),
    updatedAt: new Date("2024-02-06"),
  },
  {
    id: "prod-004",
    sku: "CAR-001",
    nombre: "Pechuga de Pollo Fresco",
    categoria: "Carnes",
    marca: "Carnes Premium",
    costoProm: 280,
    precioVenta: 599,
    stock: 120,
    unidadMedida: "kg",
    proveedor: "Matadero Central",
    margenPorcentaje: 53.3,
    margenDolar: 319,
    rotacionDias: 1,
    ventasUltimos3Meses: 4800,
    ventasUltimos6Meses: 9600,
    ventasUltimos12Meses: 19200,
    createdAt: new Date("2024-01-15"),
    updatedAt: new Date("2024-02-06"),
  },
  {
    id: "prod-005",
    sku: "FRU-001",
    nombre: "Manzanas Rojas",
    categoria: "Frutas y Verduras",
    marca: "Frutas de la Región",
    costoProm: 120,
    precioVenta: 249,
    stock: 350,
    unidadMedida: "kg",
    proveedor: "Productores Locales",
    margenPorcentaje: 51.8,
    margenDolar: 129,
    rotacionDias: 4,
    ventasUltimos3Meses: 6500,
    ventasUltimos6Meses: 13000,
    ventasUltimos12Meses: 26000,
    createdAt: new Date("2024-01-15"),
    updatedAt: new Date("2024-02-06"),
  },
  {
    id: "prod-006",
    sku: "LIMP-001",
    nombre: "Desinfectante Multiusos",
    categoria: "Limpieza",
    marca: "Limpieza Total",
    costoProm: 85,
    precioVenta: 189,
    stock: 600,
    unidadMedida: "unid",
    proveedor: "Químicos Industriales",
    margenPorcentaje: 55.0,
    margenDolar: 104,
    rotacionDias: 6,
    ventasUltimos3Meses: 5200,
    ventasUltimos6Meses: 10400,
    ventasUltimos12Meses: 20800,
    createdAt: new Date("2024-01-15"),
    updatedAt: new Date("2024-02-06"),
  },
  {
    id: "prod-007",
    sku: "ELEC-001",
    nombre: "Lámpara LED 60W",
    categoria: "Electrónicos",
    marca: "Tech Lighting",
    costoProm: 320,
    precioVenta: 699,
    stock: 85,
    unidadMedida: "unid",
    proveedor: "Importaciones Tech",
    margenPorcentaje: 54.2,
    margenDolar: 379,
    rotacionDias: 15,
    ventasUltimos3Meses: 1200,
    ventasUltimos6Meses: 2400,
    ventasUltimos12Meses: 4800,
    createdAt: new Date("2024-01-15"),
    updatedAt: new Date("2024-02-06"),
  },
  {
    id: "prod-008",
    sku: "TEXT-001",
    nombre: "Remera Básica",
    categoria: "Textil",
    marca: "Fashion Basic",
    costoProm: 150,
    precioVenta: 399,
    stock: 220,
    unidadMedida: "unid",
    proveedor: "Confecciones Nacionales",
    margenPorcentaje: 62.4,
    margenDolar: 249,
    rotacionDias: 8,
    ventasUltimos3Meses: 3100,
    ventasUltimos6Meses: 6200,
    ventasUltimos12Meses: 12400,
    createdAt: new Date("2024-01-15"),
    updatedAt: new Date("2024-02-06"),
  },
]

// Recomendaciones IA
export const aiRecommendations: AIRecommendation[] = [
  {
    id: "rec-001",
    productId: "prod-001",
    producto: thorProducts[0],
    puntuacionConfianza: 95,
    razon: "Rotación muy rápida (3 días) + Ventas consistentes. Estacionalidad detectada.",
    tendencia: "al_alza",
    impactoEstimado: 18,
    sugerenciaAccion: "reabastecer",
    correlacionados: ["LACT-001", "BEBI-001"],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "rec-002",
    productId: "prod-003",
    producto: thorProducts[2],
    puntuacionConfianza: 88,
    razon: "Margen alto (60.7%) + Rotación 2 días. Producto estrella.",
    tendencia: "al_alza",
    impactoEstimado: 22,
    sugerenciaAccion: "promocionar",
    correlacionados: ["PAN-001", "BEBI-001"],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "rec-003",
    productId: "prod-004",
    producto: thorProducts[3],
    puntuacionConfianza: 92,
    razon: "Rotación 1 día + Margen 53.3%. Demanda muy alta.",
    tendencia: "al_alza",
    impactoEstimado: 25,
    sugerenciaAccion: "reabastecer",
    correlacionados: ["CAR-001", "FRU-001"],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
]

// Vendedores
export const vendedores: Vendedor[] = [
  {
    id: "vend-001",
    nombre: "Juan",
    apellido: "García",
    email: "juan.garcia@empresa.com",
    telefono: "011-2345-6789",
    foto: "https://api.dicebear.com/7.x/avataaars/svg?seed=Juan",
    estado: "activo",
    fechaAlta: new Date("2023-01-15"),
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "vend-002",
    nombre: "María",
    apellido: "López",
    email: "maria.lopez@empresa.com",
    telefono: "011-2345-6790",
    foto: "https://api.dicebear.com/7.x/avataaars/svg?seed=Maria",
    estado: "activo",
    fechaAlta: new Date("2023-02-20"),
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "vend-003",
    nombre: "Carlos",
    apellido: "Rodríguez",
    email: "carlos.rodriguez@empresa.com",
    telefono: "011-2345-6791",
    foto: "https://api.dicebear.com/7.x/avataaars/svg?seed=Carlos",
    estado: "activo",
    fechaAlta: new Date("2023-03-10"),
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "vend-004",
    nombre: "Ana",
    apellido: "Martínez",
    email: "ana.martinez@empresa.com",
    telefono: "011-2345-6792",
    foto: "https://api.dicebear.com/7.x/avataaars/svg?seed=Ana",
    estado: "activo",
    fechaAlta: new Date("2023-04-05"),
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "vend-005",
    nombre: "Roberto",
    apellido: "Fernández",
    email: "roberto.fernandez@empresa.com",
    telefono: "011-2345-6793",
    foto: "https://api.dicebear.com/7.x/avataaars/svg?seed=Roberto",
    estado: "activo",
    fechaAlta: new Date("2023-05-12"),
    createdAt: new Date(),
    updatedAt: new Date(),
  },
]

// Métrica Vendedores
export const vendedoresMetricas: VendedorMetrica[] = [
  {
    vendedorId: "vend-001",
    vendedor: vendedores[0],
    periodo: new Date("2024-02-01"),
    totalVendido: 156000,
    numeroTransacciones: 485,
    ticketPromedio: 321.65,
    tasaConversion: 42.5,
    productosTopVendidos: [
      { sku: "LACT-001", nombre: "Leche Descremada 1L", unidades: 450, monto: 40050 },
      { sku: "PAN-001", nombre: "Pan de Molde Integral", unidades: 385, monto: 34265 },
      { sku: "BEBI-001", nombre: "Gaseosa 2L", unidades: 220, monto: 34980 },
    ],
    cambioVsPeriodoAnterior: 12.5,
  },
  {
    vendedorId: "vend-002",
    vendedor: vendedores[1],
    periodo: new Date("2024-02-01"),
    totalVendido: 189000,
    numeroTransacciones: 562,
    ticketPromedio: 336.3,
    tasaConversion: 48.3,
    productosTopVendidos: [
      { sku: "CAR-001", nombre: "Pechuga de Pollo Fresco", unidades: 320, monto: 191680 },
      { sku: "FRU-001", nombre: "Manzanas Rojas", unidades: 280, monto: 69720 },
      { sku: "LACT-001", nombre: "Leche Descremada 1L", unidades: 315, monto: 28035 },
    ],
    cambioVsPeriodoAnterior: 15.8,
  },
  {
    vendedorId: "vend-003",
    vendedor: vendedores[2],
    periodo: new Date("2024-02-01"),
    totalVendido: 142000,
    numeroTransacciones: 428,
    ticketPromedio: 331.77,
    tasaConversion: 39.2,
    productosTopVendidos: [
      { sku: "LIMP-001", nombre: "Desinfectante Multiusos", unidades: 350, monto: 66150 },
      { sku: "BEBI-001", nombre: "Gaseosa 2L", unidades: 210, monto: 33390 },
      { sku: "TEXT-001", nombre: "Remera Básica", unidades: 125, monto: 49875 },
    ],
    cambioVsPeriodoAnterior: 8.2,
  },
  {
    vendedorId: "vend-004",
    vendedor: vendedores[3],
    periodo: new Date("2024-02-01"),
    totalVendido: 167000,
    numeroTransacciones: 495,
    ticketPromedio: 337.37,
    tasaConversion: 45.1,
    productosTopVendidos: [
      { sku: "ELEC-001", nombre: "Lámpara LED 60W", unidades: 95, monto: 66405 },
      { sku: "PAN-001", nombre: "Pan de Molde Integral", unidades: 320, monto: 28480 },
      { sku: "LACT-001", nombre: "Leche Descremada 1L", unidades: 380, monto: 33820 },
    ],
    cambioVsPeriodoAnterior: 18.3,
  },
  {
    vendedorId: "vend-005",
    vendedor: vendedores[4],
    periodo: new Date("2024-02-01"),
    totalVendido: 128500,
    numeroTransacciones: 402,
    ticketPromedio: 319.65,
    tasaConversion: 36.8,
    productosTopVendidos: [
      { sku: "TEXT-001", nombre: "Remera Básica", unidades: 95, monto: 37905 },
      { sku: "BEBI-001", nombre: "Gaseosa 2L", unidades: 185, monto: 29415 },
      { sku: "FRU-001", nombre: "Manzanas Rojas", unidades: 210, monto: 52290 },
    ],
    cambioVsPeriodoAnterior: 5.1,
  },
]

// Cajeros
export const cajeros: Cajero[] = [
  {
    id: "caj-001",
    nombre: "Diego",
    apellido: "Gómez",
    numCaja: 1,
    email: "diego.gomez@empresa.com",
    foto: "https://api.dicebear.com/7.x/avataaars/svg?seed=Diego",
    estado: "activo",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "caj-002",
    nombre: "Sofía",
    apellido: "Torres",
    numCaja: 2,
    email: "sofia.torres@empresa.com",
    foto: "https://api.dicebear.com/7.x/avataaars/svg?seed=Sofia",
    estado: "activo",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "caj-003",
    nombre: "Marcelo",
    apellido: "Sánchez",
    numCaja: 3,
    email: "marcelo.sanchez@empresa.com",
    foto: "https://api.dicebear.com/7.x/avataaars/svg?seed=Marcelo",
    estado: "activo",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "caj-004",
    nombre: "Valentina",
    apellido: "López",
    numCaja: 4,
    email: "valentina.lopez@empresa.com",
    foto: "https://api.dicebear.com/7.x/avataaars/svg?seed=Valentina",
    estado: "activo",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "caj-005",
    nombre: "Javier",
    apellido: "Cruz",
    numCaja: 5,
    email: "javier.cruz@empresa.com",
    foto: "https://api.dicebear.com/7.x/avataaars/svg?seed=Javier",
    estado: "ausente",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
]

// Métrica Cajeros
export const cajerosMetricas: CajeroMetrica[] = [
  {
    cajeroId: "caj-001",
    cajero: cajeros[0],
    fecha: new Date("2024-02-06"),
    hora: "14:00",
    tiempoPromedioAtension: 145,
    numeroClientesAtendidos: 245,
    totalFacturado: 85400,
    tasaErrores: 0.8,
    satisfaccionCliente: 4.7,
  },
  {
    cajeroId: "caj-002",
    cajero: cajeros[1],
    fecha: new Date("2024-02-06"),
    hora: "14:00",
    tiempoPromedioAtension: 165,
    numeroClientesAtendidos: 210,
    totalFacturado: 78900,
    tasaErrores: 1.2,
    satisfaccionCliente: 4.5,
  },
  {
    cajeroId: "caj-003",
    cajero: cajeros[2],
    fecha: new Date("2024-02-06"),
    hora: "14:00",
    tiempoPromedioAtension: 128,
    numeroClientesAtendidos: 280,
    totalFacturado: 92100,
    tasaErrores: 0.5,
    satisfaccionCliente: 4.9,
  },
  {
    cajeroId: "caj-004",
    cajero: cajeros[3],
    fecha: new Date("2024-02-06"),
    hora: "14:00",
    tiempoPromedioAtension: 152,
    numeroClientesAtendidos: 235,
    totalFacturado: 81500,
    tasaErrores: 0.9,
    satisfaccionCliente: 4.6,
  },
  {
    cajeroId: "caj-005",
    cajero: cajeros[4],
    fecha: new Date("2024-02-06"),
    hora: "14:00",
    tiempoPromedioAtension: 0,
    numeroClientesAtendidos: 0,
    totalFacturado: 0,
    tasaErrores: 0,
    satisfaccionCliente: 0,
  },
]

// Competidores
export const competidores: Competidor[] = [
  {
    id: "comp-001",
    nombre: "Supermercado ABC",
    sitioWeb: "https://superabc.com",
    telefono: "011-1234-5678",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "comp-002",
    nombre: "Mayorista XYZ",
    sitioWeb: "https://mayoristaxyz.com",
    telefono: "011-8765-4321",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "comp-003",
    nombre: "Distribuidora Delta",
    sitioWeb: "https://distribuidora-delta.com",
    telefono: "011-5555-5555",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
]

// Precios Competencia
export const preciosCompetencia: PrecioCompetidor[] = [
  {
    id: "pc-001",
    competidorId: "comp-001",
    productoSku: "LACT-001",
    productoNombre: "Leche Descremada 1L",
    nuestroPrecio: 89,
    precioCompetidor: 95,
    diferenciaProcentaje: -6.3,
    ultimaActualizacion: new Date("2024-02-05"),
    fuente: "web_scraping",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "pc-002",
    competidorId: "comp-002",
    productoSku: "BEBI-001",
    productoNombre: "Gaseosa 2L",
    nuestroPrecio: 159,
    precioCompetidor: 155,
    diferenciaProcentaje: 2.5,
    ultimaActualizacion: new Date("2024-02-05"),
    fuente: "web_scraping",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "pc-003",
    competidorId: "comp-001",
    productoSku: "PAN-001",
    productoNombre: "Pan de Molde Integral",
    nuestroPrecio: 89,
    precioCompetidor: 85,
    diferenciaProcentaje: 4.7,
    ultimaActualizacion: new Date("2024-02-05"),
    fuente: "ocr_imagen",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
]

// Histórico Ventas
export const historicoVentas: HistoricoVenta[] = Array.from({ length: 24 }, (_, i) => {
  const date = new Date()
  date.setMonth(date.getMonth() - (23 - i))
  const baseVentas = 450000
  const estacionalidad = Math.sin((i * Math.PI) / 6) * 80000
  const ruido = (Math.random() - 0.5) * 40000
  return {
    fecha: date,
    ventas: baseVentas + estacionalidad + ruido,
    transacciones: Math.floor(1200 + Math.random() * 400),
    ticketPromedio: 325 + Math.random() * 75,
    productosMasVendidos: ["LACT-001", "PAN-001", "BEBI-001"],
  }
})

export function obtenerTopProductosPorMargen() {
  return thorProducts.sort((a, b) => b.margenDolar - a.margenDolar).slice(0, 10)
}

export function calcularKPIsMensuales() {
  const ventasTotales = historicoVentas[historicoVentas.length - 1].ventas
  const ventasMesAnterior = historicoVentas[historicoVentas.length - 2].ventas
  const cambioMes = ((ventasTotales - ventasMesAnterior) / ventasMesAnterior) * 100

  const margenPromedio =
    thorProducts.reduce((sum, p) => sum + p.margenPorcentaje, 0) / thorProducts.length

  const ticketPromedio = historicoVentas[historicoVentas.length - 1].ticketPromedio

  const numeroTransacciones = historicoVentas[historicoVentas.length - 1].transacciones

  const rotacionPromedio =
    thorProducts.reduce((sum, p) => sum + p.rotacionDias, 0) / thorProducts.length

  return {
    ventasTotales,
    cambioMes,
    margenPromedio,
    ticketPromedio,
    numeroTransacciones,
    rotacionPromedio,
  }
}
