import { Warehouse, Product, ReceiptOrder, ShippingOrder, WMSAlert, WMSMetrics } from './wms-types'

// ALMACENES
export const warehouses: Warehouse[] = [
  {
    id: 'wh-001',
    code: 'ALM-001',
    name: 'Almacén Principal',
    type: 'principal',
    address: 'Ruta 5 Km 42, GBA',
    capacity: 5000,
    capacityUnit: 'm3',
    temperature_controlled: true,
    supervisor: 'Juan García',
    zones: [],
    occupancy_percentage: 72,
    status: 'activo',
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-01'),
  },
  {
    id: 'wh-002',
    code: 'ALM-002',
    name: 'Almacén Satélite CABA',
    type: 'satelite',
    address: 'Av. Corrientes 1000, CABA',
    capacity: 1500,
    capacityUnit: 'm3',
    temperature_controlled: false,
    supervisor: 'María López',
    zones: [],
    occupancy_percentage: 55,
    status: 'activo',
    createdAt: new Date('2024-01-15'),
    updatedAt: new Date('2024-01-15'),
  },
]

// PRODUCTOS
export const products: Product[] = [
  {
    id: 'prod-001',
    sku: 'LAPTOP-001',
    name: 'Laptop Dell XPS 13',
    description: 'Laptop de 13" para profesionales',
    category: 'Electrónica',
    uom: 'unid',
    requiresBatch: false,
    requiresSerial: true,
    requiresExpiration: false,
    minStock: 10,
    maxStock: 50,
    reorderPoint: 15,
    valuationMethod: 'PROM',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'prod-002',
    sku: 'ACEITE-001',
    name: 'Aceite de Motor Premium',
    description: 'Aceite sintético para motores',
    category: 'Lubricantes',
    uom: 'lts',
    requiresBatch: true,
    requiresSerial: false,
    requiresExpiration: true,
    minStock: 100,
    maxStock: 500,
    reorderPoint: 150,
    valuationMethod: 'FIFO',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'prod-003',
    sku: 'CABLES-001',
    name: 'Cable USB-C',
    category: 'Accesorios',
    uom: 'unid',
    requiresBatch: true,
    requiresSerial: false,
    requiresExpiration: false,
    minStock: 200,
    maxStock: 1000,
    reorderPoint: 300,
    valuationMethod: 'PROM',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
]

// ÓRDENES DE RECEPCIÓN
export const receiptOrders: ReceiptOrder[] = [
  {
    id: 'or-001',
    code: 'OR-2024-001',
    type: 'compra',
    provider: 'Tech Solutions SA',
    warehouse: warehouses[0],
    scheduledDate: new Date('2024-02-10'),
    realDate: new Date('2024-02-10'),
    status: 'completada',
    items: [
      {
        id: 'ori-001',
        sku: 'LAPTOP-001',
        productName: 'Laptop Dell XPS 13',
        expectedQuantity: 20,
        receivedQuantity: 20,
        rejectedQuantity: 0,
        uom: 'unid',
        unitPrice: 85000,
        qualityInspection: 'ok',
      },
    ],
    totalItems: 20,
    receivedItems: 20,
    documentReference: 'OC-2024-5432',
    carrier: 'Transporte Express',
    approvalStatus: 'aprobada',
    approvedBy: 'Admin',
    approvalDate: new Date('2024-02-10'),
    createdAt: new Date('2024-02-09'),
    updatedAt: new Date('2024-02-10'),
  },
  {
    id: 'or-002',
    code: 'OR-2024-002',
    type: 'compra',
    provider: 'Oil Supplies Inc',
    warehouse: warehouses[0],
    scheduledDate: new Date('2024-02-15'),
    status: 'enproceso',
    items: [
      {
        id: 'ori-002',
        sku: 'ACEITE-001',
        productName: 'Aceite de Motor Premium',
        expectedQuantity: 250,
        receivedQuantity: 150,
        rejectedQuantity: 0,
        uom: 'lts',
        unitPrice: 450,
        batch: 'BATCH-2024-001',
        expirationDate: new Date('2025-02-15'),
        qualityInspection: 'ok',
      },
    ],
    totalItems: 250,
    receivedItems: 150,
    approvalStatus: 'pendiente',
    createdAt: new Date('2024-02-14'),
    updatedAt: new Date('2024-02-15'),
  },
]

// ÓRDENES DE SALIDA (PICKING)
export const shippingOrders: ShippingOrder[] = [
  {
    id: 'os-001',
    code: 'OS-2024-001',
    client: 'Cliente Premium SA',
    destination: 'Av. Rivadavia 5000, CABA',
    scheduledDate: new Date('2024-02-20'),
    priority: 'urgente',
    status: 'enpreparacion',
    items: [
      {
        id: 'osi-001',
        sku: 'LAPTOP-001',
        productName: 'Laptop Dell XPS 13',
        quantity: 5,
        uom: 'unid',
        pickedQuantity: 3,
        requiredSerial: 'N/A',
        status: 'enproceso',
      },
    ],
    totalItems: 5,
    pickedItems: 3,
    operario: 'Carlos Ruiz',
    createdAt: new Date('2024-02-19'),
    updatedAt: new Date('2024-02-20'),
  },
]

// ALERTAS
export const wmsAlerts: WMSAlert[] = [
  {
    id: 'alert-001',
    type: 'stock_bajo',
    severity: 'advertencia',
    product: products[1],
    warehouse: warehouses[0],
    message: 'Stock bajo en Aceite de Motor Premium',
    details: 'Stock actual: 150 lts, Mínimo requerido: 100 lts',
    resolved: false,
    createdAt: new Date('2024-02-15'),
    updatedAt: new Date('2024-02-15'),
  },
  {
    id: 'alert-002',
    type: 'vencimiento_proximo',
    severity: 'critico',
    product: products[1],
    message: 'Producto con vencimiento próximo',
    details: 'Lote BATCH-2024-001 vence en 15 días',
    resolved: false,
    createdAt: new Date('2024-02-16'),
    updatedAt: new Date('2024-02-16'),
  },
  {
    id: 'alert-003',
    type: 'orden_retrasada',
    severity: 'advertencia',
    message: 'Orden de recepción retrasada',
    details: 'OR-2024-002 debió llegar hace 2 horas',
    resolved: false,
    createdAt: new Date('2024-02-15'),
    updatedAt: new Date('2024-02-15'),
  },
]

// MÉTRICAS
export const wmsMetrics: WMSMetrics = {
  occupancyPercentage: 68,
  totalInventoryValue: 2450000,
  activeOrders: {
    receptions: 2,
    shipments: 5,
    picking: 3,
  },
  criticalAlerts: 1,
  inventoryAccuracy: 98.5,
  lastCountDate: new Date('2024-02-10'),
  averageLeadTime: 4.2, // horas
  inventoryTurnover: 8.3, // mensual
}
